// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQJeHRDQRJ0GbL1LoejmgafP16VWsh1rc',
    appId: '1:449651094702:web:6e3b623c40af1a4277693f',
    messagingSenderId: '449651094702',
    projectId: 'muzium-fyp',
    authDomain: 'muzium-fyp.firebaseapp.com',
    storageBucket: 'muzium-fyp.firebasestorage.app',
    measurementId: 'G-DY4L3FF3Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD74Vvuih__il9wxX331Xiu4rPc_cQV7Qo',
    appId: '1:449651094702:android:d097edf754c1694a77693f',
    messagingSenderId: '449651094702',
    projectId: 'muzium-fyp',
    storageBucket: 'muzium-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB65qD-RakQM5KEFm2DUCYWgqqoAzf1znU',
    appId: '1:449651094702:ios:21d706577bfe3f9977693f',
    messagingSenderId: '449651094702',
    projectId: 'muzium-fyp',
    storageBucket: 'muzium-fyp.firebasestorage.app',
    iosBundleId: 'com.example.muziumFyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB65qD-RakQM5KEFm2DUCYWgqqoAzf1znU',
    appId: '1:449651094702:ios:21d706577bfe3f9977693f',
    messagingSenderId: '449651094702',
    projectId: 'muzium-fyp',
    storageBucket: 'muzium-fyp.firebasestorage.app',
    iosBundleId: 'com.example.muziumFyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQJeHRDQRJ0GbL1LoejmgafP16VWsh1rc',
    appId: '1:449651094702:web:abc57bc69425b11677693f',
    messagingSenderId: '449651094702',
    projectId: 'muzium-fyp',
    authDomain: 'muzium-fyp.firebaseapp.com',
    storageBucket: 'muzium-fyp.firebasestorage.app',
    measurementId: 'G-4BQM5BHBEP',
  );
}
